# FedML TRAINING PLATFORM
FEDML_TRAINING_PLATFORM_SIMULATION = "simulation"
FEDML_TRAINING_PLATFORM_CROSS_SILO = "cross_silo"
FEDML_TRAINING_PLATFORM_CROSS_DEVICE = "cross_device"
FEDML_TRAINING_PLATFORM_DISTRIBUTED = "distributed"

# FedML TRAINING PLATFORM TYPE
FEDML_TRAINING_PLATFORM_CROSS_SILO_TYPE = 1
FEDML_TRAINING_PLATFORM_SIMULATION_TYPE = 2
FEDML_TRAINING_PLATFORM_DISTRIBUTED_TYPE = 3
FEDML_TRAINING_PLATFORM_CROSS_DEVICE_TYPE = 4

# FedML CROSS-SILO SCENARIO
FEDML_CROSS_SILO_SCENARIO_HORIZONTAL = "horizontal"
FEDML_CROSS_SILO_SCENARIO_HIERARCHICAL = "hierarchical"

# FedML SIMULATION TYPE
FEDML_SIMULATION_TYPE_SP = "sp"
FEDML_SIMULATION_TYPE_MPI = "MPI"
FEDML_SIMULATION_TYPE_NCCL = "NCCL"

# FedML data
FA_DATA_CACHE_FOLDER = "data"
FA_DATA_TWITTER_Sentiment140_URL = "http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip"

# task
FA_TASK_AVG = "AVG"
FA_TASK_HEAVY_HITTER_TRIEHH = "heavy_hitter"



